<a href="https://colab.research.google.com/github/ryukrodit/assignment-/blob/main/RoditNepal_2358289_Worksheet0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Task-1 Unit Conversion

In [1]:
def convert_length(value, unit):
    if unit == 'm_to_ft':
        return value * 3.28084
    elif unit == 'ft_to_m':
        return value / 3.28084
    else:
        raise ValueError("Invalid unit for length conversion.")

def convert_weight(value, unit):
    if unit == 'kg_to_lbs':
        return value * 2.20462
    elif unit == 'lbs_to_kg':
        return value / 2.20462
    else:
        raise ValueError("Invalid unit for weight conversion.")

def convert_volume(value, unit):
    if unit == 'L_to_gal':
        return value * 0.264172
    elif unit == 'gal_to_L':
        return value / 0.264172
    else:
        raise ValueError("Invalid unit for volume conversion.")

def main():
    print("Welcome to the Unit Converter!")
    print("Available conversions:")
    print("1. Length: meters to feet, feet to meters")
    print("2. Weight: kilograms to pounds, pounds to kilograms")
    print("3. Volume: liters to gallons, gallons to liters")

    try:
        conversion_type = int(input("Choose the type of conversion (1, 2, or 3): "))
        value = float(input("Enter the value to be converted: "))

        if conversion_type == 1:
            unit = input("Choose conversion (m_to_ft or ft_to_m): ")
            result = convert_length(value, unit)
            print(f"Converted value: {result}")
        elif conversion_type == 2:
            unit = input("Choose conversion (kg_to_lbs or lbs_to_kg): ")
            result = convert_weight(value, unit)
            print(f"Converted value: {result}")
        elif conversion_type == 3:
            unit = input("Choose conversion (L_to_gal or gal_to_L): ")
            result = convert_volume(value, unit)
            print(f"Converted value: {result}")
        else:
            print("Invalid conversion type selected.")
    except ValueError as e:
        print(f"Error: {e}")

main()

Welcome to the Unit Converter!
Available conversions:
1. Length: meters to feet, feet to meters
2. Weight: kilograms to pounds, pounds to kilograms
3. Volume: liters to gallons, gallons to liters
Choose the type of conversion (1, 2, or 3): 3
Enter the value to be converted: liters
Error: could not convert string to float: 'liters'


# Task-2 Math Operation on List of Numbers

In [2]:
def calculate_sum(numbers):
    """
    Calculates the sum of a list of numbers.

    Parameters:
    numbers (list): A list of numbers.

    Returns:
    float: The sum of the numbers.
    """
    return sum(numbers)

def calculate_average(numbers):
    """
    Calculates the average of a list of numbers.

    Parameters:
    numbers (list): A list of numbers.

    Returns:
    float: The average of the numbers.
    """
    return sum(numbers) / len(numbers)

def find_maximum(numbers):
    """
    Finds the maximum value in a list of numbers.

    Parameters:
    numbers (list): A list of numbers.

    Returns:
    float: The maximum value.
    """
    return max(numbers)

def find_minimum(numbers):
    """
    Finds the minimum value in a list of numbers.

    Parameters:
    numbers (list): A list of numbers.

    Returns:
    float: The minimum value.
    """
    return min(numbers)

def main():
    print("Welcome to the Mathematical Operations Program!")
    print("Available operations:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    try:
        operation = int(input("Choose the operation (1, 2, 3, or 4): "))
        numbers = list(map(float, input("Enter a list of numbers separated by spaces: ").split()))

        if operation == 1:
            result = calculate_sum(numbers)
            print(f"Sum: {result}")
        elif operation == 2:
            result = calculate_average(numbers)
            print(f"Average: {result}")
        elif operation == 3:
            result = find_maximum(numbers)
            print(f"Maximum: {result}")
        elif operation == 4:
            result = find_minimum(numbers)
            print(f"Minimum: {result}")
        else:
            print("Invalid operation selected.")
    except ValueError as e:
        print(f"Error: {e}")
    except ZeroDivisionError:
        print("Error: Cannot calculate average of an empty list.")

main()

Welcome to the Mathematical Operations Program!
Available operations:
1. Sum
2. Average
3. Maximum
4. Minimum
Choose the operation (1, 2, 3, or 4): 4
Enter a list of numbers separated by spaces: 2
Minimum: 2.0


# Exercise on List Manipulation:

In [3]:
def extract_every_other(lst):
    """
    Extracts every other element from a list, starting from the first element.

    Parameters:
    lst (list): The input list.

    Returns:
    list: A new list containing every other element.
    """
    return lst[::2]

extract_every_other([1, 2, 3, 4, 5, 6], )

[1, 3, 5]

In [4]:
def get_sublist(lst, start, end):
    """
    Returns a sublist from a given list, starting from a specified index and ending at another specified index.

    Parameters:
    lst (list): The input list.
    start (int): The starting index.
    end (int): The ending index.

    Returns:
    list: The sublist from start to end (inclusive).
    """
    return lst[start:end+1]

get_sublist([1, 2, 3, 4, 5, 6],2,4)

[3, 4, 5]

In [5]:
def reverse_list(lst):
    """
    Reverses a list using slicing.

    Parameters:
    lst (list): The input list.

    Returns:
    list: The reversed list.
    """
    return lst[::-1]

reverse_list([1, 2, 3, 4, 5])

[5, 4, 3, 2, 1]

In [6]:
def remove_first_last(lst):
    """
    Removes the first and last elements of a list and returns the resulting sublist.

    Parameters:
    lst (list): The input list.

    Returns:
    list: The sublist without the first and last elements.
    """
    return lst[1:-1]

remove_first_last([1, 2, 3, 4, 5])

[2, 3, 4]

In [7]:
def get_first_n(lst, n):
    """
    Extracts the first n elements from a list.

    Parameters:
    lst (list): The input list.
    n (int): The number of elements to extract.

    Returns:
    list: The first n elements of the list.
    """
    return lst[:n]

get_first_n([1, 2, 3, 4, 5],3)

[1, 2, 3]

In [8]:
def get_last_n(lst, n):
    """
    Extracts the last n elements of a list using slicing.

    Parameters:
    lst (list): The input list.
    n (int): The number of elements to extract.

    Returns:
    list: The last n elements of the list.
    """
    return lst[-n:]

get_last_n([1, 2, 3, 4, 5],2)

[4, 5]

In [9]:
def reverse_skip(lst):
    """
    Extracts a list of elements in reverse order starting from the second-to-last element and skipping one element in between.

    Parameters:
    lst (list): The input list.

    Returns:
    list: A new list containing every second element starting from the second-to-last, moving backward.
    """
    return lst[-2::-2]

reverse_skip([1, 2, 3, 4, 5, 6])

[5, 3, 1]

# Exercise on Nested List

In [10]:
def flatten(lst):
    """
    Flattens a nested list into a single list.

    Parameters:
    lst (list): The nested list.

    Returns:
    list: A flattened version of the list.
    """
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(flatten(item))
        else:
            flat_list.append(item)
    return flat_list

flatten([[1, 2], [3, [4, 5]], 6])

[1, 2, 3, 4, 5, 6]

In [11]:
def access_nested_element(lst, indices):
    """
    Extracts a specific element from a nested list given its indices.

    Parameters:
    lst (list): The nested list.
    indices (list): A list of indices.

    Returns:
    any: The element at the specified position.
    """
    for index in indices:
        lst = lst[index]
    return lst
access_nested_element([[1, 2, 3], [4, 5, 6], [7, 8, 9]],[1,2])

6

In [12]:
def sum_nested(lst):
    """
    Calculates the sum of all the numbers in a nested list.

    Parameters:
    lst (list): The nested list.

    Returns:
    float: The sum of all elements.
    """
    return sum(flatten(lst))

sum_nested([[1, 2], [3, [4, 5]], 6])

21

In [13]:
def remove_element(lst, elem):
    """
    Removes all occurrences of a specific element from a nested list.

    Parameters:
    lst (list): The nested list.
    elem (any): The element to remove.

    Returns:
    list: The modified list.
    """
    return [remove_element(item, elem) if isinstance(item, list) else item for item in lst if item != elem]

remove_element([[1, 2], [3, 2], [4, 5]],2)

[[1], [3], [4, 5]]

In [14]:
def find_max(lst):
    """
    Finds the maximum element in a nested list.

    Parameters:
    lst (list): The nested list.

    Returns:
    float: The maximum element.
    """
    return max(flatten(lst))

find_max([[1, 2], [3, [4, 5]], 6])

6

In [15]:
def count_occurrences(lst, elem):
    """
    Counts how many times a specific element appears in a nested list.

    Parameters:
    lst (list): The nested list.
    elem (any): The element to count.

    Returns:
    int: The number of occurrences.
    """
    return flatten(lst).count(elem)
count_occurrences([[1, 2], [2, 3], [2, 4]],2)

3

In [16]:
def deep_flatten(lst):
    """
    Flattens a deeply nested list into a single list.

    Parameters:
    lst (list): The deeply nested list.

    Returns:
    list: A single flattened list.
    """
    return flatten(lst)

deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

[1, 2, 3, 4, 5, 6, 7, 8]

In [17]:
def average_nested(lst):
    """
    Calculates the average of all elements in a nested list.

    Parameters:
    lst (list): The nested list.

    Returns:
    float: The average of all elements.
    """
    flat_list = flatten(lst)
    return sum(flat_list) / len(flat_list)
average_nested([[1, 2], [3, 4], [5, 6]])

3.5

# Basic Vector and Matrix Operation with Numpy.

# Problem - 1: Array Creation:

In [18]:
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("Empty 2x2 Array:\n", empty_array)
print("---------------")

# 2. Initialize an all ones array with size 4x2
ones_array = np.ones((4, 2))
print("All Ones 4x2 Array:\n", ones_array)
print("---------------")

# 3. Return a new array of given shape and type, filled with fill value
fill_value_array = np.full((3, 3), 5)  # Shape: 3x3, Fill Value: 5
print("Array Filled with Value 5:\n", fill_value_array)
print("---------------")

# 4. Return a new array of zeros with same shape and type as a given array
given_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(given_array)
print("Zeros Array with Same Shape as Given Array:\n", zeros_like_array)
print("---------------")

# 5. Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(given_array)
print("Ones Array with Same Shape as Given Array:\n", ones_like_array)
print("---------------")

# 6. Convert a list to a NumPy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("Converted NumPy Array from List:\n", numpy_array)

Empty 2x2 Array:
 [[1.8544447e-316 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000]]
---------------
All Ones 4x2 Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
---------------
Array Filled with Value 5:
 [[5 5 5]
 [5 5 5]
 [5 5 5]]
---------------
Zeros Array with Same Shape as Given Array:
 [[0 0]
 [0 0]]
---------------
Ones Array with Same Shape as Given Array:
 [[1 1]
 [1 1]]
---------------
Converted NumPy Array from List:
 [1 2 3 4]


# Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [19]:
# 1. Create an array with values ranging from 10 to 49
range_array = np.arange(10, 50)
print("Array with Values from 10 to 49:\n", range_array)
print("---------------")

# 2. Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("3x3 Matrix with Values 0 to 8:\n", matrix_3x3)
print("---------------")

# 3. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("3x3 Identity Matrix:\n", identity_matrix)
print("---------------")

# 4. Create a random array of size 30 and find the mean
random_array = np.random.random(30)
mean_value = random_array.mean()
print("Random Array of Size 30:\n", random_array)
print("Mean of Random Array:", mean_value)
print("---------------")

# 5. Create a 10x10 array with random values and find the min and max
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("10x10 Random Array:\n", random_10x10)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)
print("---------------")

# 6. Create a zero array of size 10 and replace the 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1  # Indexing starts from 0
print("Zero Array with 5th Element Replaced:\n", zero_array)
print("---------------")

# 7. Reverse an array
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("Reversed Array:\n", reversed_arr)
print("---------------")

# 8. Create a 2D array with 1 on the border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("2D Array with 1 on Border and 0 Inside:\n", border_array)
print("---------------")

# 9. Create an 8x8 checkerboard pattern
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("8x8 Checkerboard Pattern:\n", checkerboard)

Array with Values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
---------------
3x3 Matrix with Values 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
---------------
3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
---------------
Random Array of Size 30:
 [0.38448938 0.43768637 0.92378263 0.94931147 0.77560277 0.24525666
 0.00674651 0.67792495 0.45044995 0.28953639 0.82486153 0.44355754
 0.83800254 0.21821171 0.56095343 0.76037206 0.47809656 0.2973201
 0.0492256  0.16382319 0.09832909 0.68746291 0.30511466 0.37226725
 0.44953252 0.49786218 0.16167459 0.14515501 0.89942276 0.50742085]
Mean of Random Array: 0.4633151041676522
---------------
10x10 Random Array:
 [[4.92832189e-01 7.81140273e-01 8.04630845e-01 4.36914948e-01
  5.96413438e-01 6.11090317e-01 4.51246480e-02 8.72590184e-01
  5.61718050e-01 4.44246382e-02]
 [8.83240284e-02 6.51794485e-01 7.76798270e-01 3.01017549e-01
  3.01213807e-01 5

# Problem - 3: Array Operations:

In [20]:
# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
add_result = x + y
print("Addition of x and y:\n", add_result)
print("---------------")

# 2. Subtract the two arrays
subtract_result = x - y
print("Subtraction of x and y:\n", subtract_result)
print("---------------")

# 3. Multiply the array with an integer
multiply_result = x * 2
print("Multiplication of x by 2:\n", multiply_result)
print("---------------")

# 4. Find the square of each element
square_result = np.square(x)
print("Square of Each Element in x:\n", square_result)
print("---------------")

# 5. Find the dot product
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("Dot Product of v and w:", dot_vw)
print("Dot Product of x and v:", dot_xv)
print("Dot Product of x and y:\n", dot_xy)
print("---------------")

# 6. Concatenate x and y along rows, and v and w along columns
concatenate_rows = np.concatenate((x, y), axis=0)
concatenate_columns = np.vstack((v, w))
print("Concatenate x and y along rows:\n", concatenate_rows)
print("Concatenate v and w along columns:\n", concatenate_columns)
print("---------------")

# 7. Concatenate x and v (will raise an error)
try:
    concatenate_xv = np.concatenate((x, v))
except ValueError as e:
    print("Error:", e)
    print("Explanation: Shapes of x (2x2) and v (2,) are not compatible for concatenation.")

Addition of x and y:
 [[ 6  8]
 [10 13]]
---------------
Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]
---------------
Multiplication of x by 2:
 [[ 2  4]
 [ 6 10]]
---------------
Square of Each Element in x:
 [[ 1  4]
 [ 9 25]]
---------------
Dot Product of v and w: 219
Dot Product of x and v: [29 77]
Dot Product of x and y:
 [[19 22]
 [50 58]]
---------------
Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along columns:
 [[ 9 10]
 [11 12]]
---------------
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: Shapes of x (2x2) and v (2,) are not compatible for concatenation.


# Problem - 4: Matrix Operations:

In [21]:
# Given arrays
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A.A^-1 = I
A_inv = np.linalg.inv(A)
identity_check = np.dot(A, A_inv)
print("A.A^-1:\n", identity_check)
print("---------------")

# 2. Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB:\n", AB)
print("BA:\n", BA)
print("Is AB != BA?", not np.array_equal(AB, BA))
print("---------------")

# 3. Prove (AB)^T = B^T A^T
AB_transpose = AB.T
B_transpose_A_transpose = np.dot(B.T, A.T)
print("(AB)^T:\n", AB_transpose)
print("B^T A^T:\n", B_transpose_A_transpose)
print("Is (AB)^T == B^T A^T?", np.array_equal(AB_transpose, B_transpose_A_transpose))
print("---------------")

# Solve the system of linear equations
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

# Matrix form: AX = B
A_eq = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_eq = np.array([-1, -3, 9])
print("---------------")

# Solve using inverse method
X = np.dot(np.linalg.inv(A_eq), B_eq)
print("Solution using Inverse Method:", X)
print("---------------")

# Solve using np.linalg.solve
X_solve = np.linalg.solve(A_eq, B_eq)
print("Solution using np.linalg.solve:", X_solve)

A.A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
---------------
AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
Is AB != BA? True
---------------
(AB)^T:
 [[23 51]
 [13 29]]
B^T A^T:
 [[23 51]
 [13 29]]
Is (AB)^T == B^T A^T? True
---------------
---------------
Solution using Inverse Method: [ 2.  1. -2.]
---------------
Solution using np.linalg.solve: [ 2.  1. -2.]


# Experiment: How Fast is Numpy?

In [22]:
import time
import numpy as np

# Function to measure time taken for an operation
def measure_time(func, *args):
    start_time = time.time()
    func(*args)
    end_time = time.time()
    return end_time - start_time

# 1. Element-wise Addition
def elementwise_addition_python(list1, list2):
    return [a + b for a, b in zip(list1, list2)]

def elementwise_addition_numpy(array1, array2):
    return array1 + array2

# 2. Element-wise Multiplication
def elementwise_multiplication_python(list1, list2):
    return [a * b for a, b in zip(list1, list2)]

def elementwise_multiplication_numpy(array1, array2):
    return array1 * array2

# 3. Dot Product
def dot_product_python(list1, list2):
    return sum(a * b for a, b in zip(list1, list2))

def dot_product_numpy(array1, array2):
    return np.dot(array1, array2)

# 4. Matrix Multiplication
def matrix_multiplication_python(matrix1, matrix2):
    result = [[sum(a * b for a, b in zip(row, col)) for col in zip(*matrix2)] for row in matrix1]
    return result

def matrix_multiplication_numpy(matrix1, matrix2):
    return np.dot(matrix1, matrix2)

# Initialize data
size = 1000000
list1 = list(range(size))
list2 = list(range(size, 2 * size))
array1 = np.arange(size)
array2 = np.arange(size, 2 * size)

matrix_size = 1000
matrix1 = [[i + j for j in range(matrix_size)] for i in range(matrix_size)]
matrix2 = [[i - j for j in range(matrix_size)] for i in range(matrix_size)]
np_matrix1 = np.array(matrix1)
np_matrix2 = np.array(matrix2)

# Measure time for each operation
print("1. Element-wise Addition:")
time_python_add = measure_time(elementwise_addition_python, list1, list2)
time_numpy_add = measure_time(elementwise_addition_numpy, array1, array2)
print(f"Python Lists: {time_python_add:.6f} seconds")
print(f"NumPy Arrays: {time_numpy_add:.6f} seconds")

print("\n2. Element-wise Multiplication:")
time_python_mul = measure_time(elementwise_multiplication_python, list1, list2)
time_numpy_mul = measure_time(elementwise_multiplication_numpy, array1, array2)
print(f"Python Lists: {time_python_mul:.6f} seconds")
print(f"NumPy Arrays: {time_numpy_mul:.6f} seconds")

print("\n3. Dot Product:")
time_python_dot = measure_time(dot_product_python, list1, list2)
time_numpy_dot = measure_time(dot_product_numpy, array1, array2)
print(f"Python Lists: {time_python_dot:.6f} seconds")
print(f"NumPy Arrays: {time_numpy_dot:.6f} seconds")

print("\n4. Matrix Multiplication:")
time_python_matmul = measure_time(matrix_multiplication_python, matrix1, matrix2)
time_numpy_matmul = measure_time(matrix_multiplication_numpy, np_matrix1, np_matrix2)
print(f"Python Lists: {time_python_matmul:.6f} seconds")
print(f"NumPy Arrays: {time_numpy_matmul:.6f} seconds")

1. Element-wise Addition:
Python Lists: 0.125881 seconds
NumPy Arrays: 0.009413 seconds

2. Element-wise Multiplication:
Python Lists: 0.113497 seconds
NumPy Arrays: 0.003071 seconds

3. Dot Product:
Python Lists: 0.115335 seconds
NumPy Arrays: 0.001768 seconds

4. Matrix Multiplication:
Python Lists: 169.133233 seconds
NumPy Arrays: 4.223803 seconds
